FROM hirooka/chukasa:0.0.1-SNAPSHOT-NO-DB

MAINTAINER hirooka

#ADD chukasa-0.0.1-SNAPSHOT.jar chukasa.jar
##ADD chukasa-0.0.1-SNAPSHOT.jar /opt/chukasa/chukasa.jar
##WORKDIR /opt/chukasa/

EXPOSE 80
ENTRYPOINT ["/bin/bash", "/startup.sh"]